apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-developer-platform-api-deployment
  labels:
    app: internal-developer-platform-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-developer-platform-api
  strategy: {}
  template:
    metadata:
      name: internal-developer-platform-api-deployment
      labels:
        app: internal-developer-platform-api
    spec:
      containers:
        - name: internal-developer-platform-api
          image: rafaelcmd/internal-developer-platform-api:v2
          volumeMounts:
            - mountPath: "/.aws"
              name: aws-credentials
              readOnly: true
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/.aws/credentials"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /resource-provisioner
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /resource-provisioner
              port: 5000
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 30
      restartPolicy: Always

      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
