apiVersion: v1
kind: Service
metadata:
  name: internal-developer-platform-api
spec:
  type: NodePort
  selector:
    app: internal-developer-platform-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000