name: API - Create AWS Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/apps/provisioner_api/prod/**'
      - 'infra/modules/aws/**'
      - 'infra/shared/datadog/**'

permissions:
  contents: read

jobs:
  create-infrastructure:
    name: Create AWS Infrastructure
    runs-on: ubuntu-latest

    outputs:
      datadog_forwarder_arn: ${{ steps.terraform_output.outputs.datadog_forwarder_arn }}

    defaults:
      run:
        working-directory: infra/apps/provisioner_api/prod
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var="datadog_api_key=${{ secrets.DATADOG_API_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var="datadog_api_key=${{ secrets.DATADOG_API_KEY }}"

      - name: Get Terraform Outputs
        id: terraform_output
        run: |
          echo "datadog_forwarder_arn=$(terraform output -raw datadog_forwarder_arn)" >> $GITHUB_OUTPUT

  aws-datadog-integration:
    name: Create Datadog Integration
    runs-on: ubuntu-latest
    needs: create-infrastructure

    defaults:
      run:
        working-directory: infra/shared/datadog
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false \
            -var="datadog_api_key=${{ secrets.DATADOG_API_KEY }}" \
            -var="datadog_app_key=${{ secrets.DATADOG_APP_KEY_PROV_API }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="datadog_forwarder_arn=${{ needs.create-infrastructure.outputs.datadog_forwarder_arn }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
            -var="datadog_api_key=${{ secrets.DATADOG_API_KEY }}" \
            -var="datadog_app_key=${{ secrets.DATADOG_APP_KEY_PROV_API }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="datadog_forwarder_arn=${{ needs.create-infrastructure.outputs.datadog_forwarder_arn }}"
