name: AWS ECR - Create

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-ecr:
    name: Create ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/live/shared/ecr
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Push Datadog Agent Image
        run: |
          # Get ECR URL from Terraform output
          ECR_URL=$(terraform output -raw repository_url)
          
          # Login to Private ECR
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_URL

          # Login to Public ECR (to avoid rate limits)
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          
          # Pull Datadog Agent
          docker pull public.ecr.aws/datadog/agent:latest
          
          # Tag for Private ECR
          docker tag public.ecr.aws/datadog/agent:latest $ECR_URL:datadog-agent
          
          # Push to Private ECR
          docker push $ECR_URL:datadog-agent
